### ISSUE TITLE
Interaction failed

### ISSUE THREAD

**Issue by MrFoxyOfficial** [ShadowLp174/poll-bot#1]
Hello. 

I and my community have been experiencing issues with interacting with the bot. Some of them were able to interact while others were not able to.

There are also no errors in the logs, so I could see what the issue might be. 
![image](https://user-images.githubusercontent.com/1783339/188242906-1de61ee6-8fd3-4b9b-8b80-58893d14d98c.png)

All I've changed was config.json and that's it.

**Comment by ShadowLp174** [comment]
Well uhhh.. some logs would be really helpful :)

**Comment by MrFoxyOfficial** [comment]
@ShadowLp174 

From the original post:
> There are also no errors in the logs, so I could see what the issue might be.

**Comment by ShadowLp174** [comment]
Oh... Bruh uhm this might be some discord problem...

Are these members permanently "blocked" or can they vote if they try again?

**Comment by ShadowLp174** [comment]
Because this might be a djs problem

**Comment by MrFoxyOfficial** [comment]
Unless I create a new poll, they can't vote on the existing one.

**Comment by ShadowLp174** [comment]
This is really weird... Does this happen all the time or only during some polls?

(Sorry for the delayed reactions... I'm kinda busy rn)

**Comment by MrFoxyOfficial** [comment]
I haven't tried it afterward, but if you want, I can try it again and see if it happens all the time. Doubt I'm gonna get the same amount of replies but I can certainly try xD

As for the late reply, you're good. Everyone has their own responsibilities and daily lives. Don't worry :)

**Comment by ShadowLp174** [comment]
Less people is better than nothing :D

Imma mess around with it in my tests server too

**Comment by MrFoxyOfficial** [comment]
Hey Shadow. 

Apologies for super late reply. I just got around to do it, as I needed an actual reason to use it hahaha

I just spinned the bot back up, and I still can't change the name of the ''answers'' 
![image](https://user-images.githubusercontent.com/1783339/203067660-c70e2b44-ae4f-4aaa-a677-8e26ae2c21af.png)

if I do that, it will just tell me something went wrong and output the following error: 
![image](https://user-images.githubusercontent.com/1783339/203067884-e87c5304-fb9e-4f83-b77d-0bce4aaa1e5c.png)
```Error [INTERACTION_NOT_REPLIED]: The reply to this interaction has not been sent or deferred.
    at CommandInteraction.editReply (C:\Users\deadg\Desktop\poll-bot-master\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:138:48)
    at addPoll (C:\Users\deadg\Desktop\poll-bot-master\commands\poll.js:82:27)
    at Object.execute (C:\Users\deadg\Desktop\poll-bot-master\commands\poll.js:248:9)
    at Client.<anonymous> (C:\Users\deadg\Desktop\poll-bot-master\index.js:30:17)
    at Client.emit (node:events:520:28)
    at InteractionCreateAction.handle (C:\Users\deadg\Desktop\poll-bot-master\node_modules\discord.js\src\client\actions\InteractionCreate.js:74:12)
    at Object.module.exports [as INTERACTION_CREATE] (C:\Users\deadg\Desktop\poll-bot-master\node_modules\discord.js\src\client\websocket\handlers\INTERACTION_CREATE.js:4:36)
    at WebSocketManager.handlePacket (C:\Users\deadg\Desktop\poll-bot-master\node_modules\discord.js\src\client\websocket\WebSocketManager.js:351:31)
    at WebSocketShard.onPacket (C:\Users\deadg\Desktop\poll-bot-master\node_modules\discord.js\src\client\websocket\WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (C:\Users\deadg\Desktop\poll-bot-master\node_modules\discord.js\src\client\websocket\WebSocketShard.js:301:10) {
  [Symbol(code)]: 'INTERACTION_NOT_REPLIED'```



On top of that, if I try to use the experimental (yes I'm aware it can break stuff xD), I'm getting this:
https://pastebin.com/JM7Jk9yA
